/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppCostCalculatorRouteImport } from './routes/app-cost-calculator'
import { Route as IndexRouteImport } from './routes/index'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCostCalculatorRoute = AppCostCalculatorRouteImport.update({
  id: '/app-cost-calculator',
  path: '/app-cost-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-cost-calculator': typeof AppCostCalculatorRoute
  '/blog': typeof BlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-cost-calculator': typeof AppCostCalculatorRoute
  '/blog': typeof BlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-cost-calculator': typeof AppCostCalculatorRoute
  '/blog': typeof BlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app-cost-calculator' | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app-cost-calculator' | '/blog'
  id: '__root__' | '/' | '/app-cost-calculator' | '/blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppCostCalculatorRoute: typeof AppCostCalculatorRoute
  BlogRoute: typeof BlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-cost-calculator': {
      id: '/app-cost-calculator'
      path: '/app-cost-calculator'
      fullPath: '/app-cost-calculator'
      preLoaderRoute: typeof AppCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppCostCalculatorRoute: AppCostCalculatorRoute,
  BlogRoute: BlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
